---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Ensure required packages are present"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Ensure httpd service is started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ services }}"

- name: Ensure latest index.html is present
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Whitelist http in firewalld
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_version|int >= 7
